[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "chmod +x build.sh",
    "./build.sh"
]

[start]
cmd = "python3 -m uvicorn carta_app:app --host 0.0.0.0 --port $PORT"
